### ISSUE TITLE
gevent.monkey.patch_thread() causes errors when threading before importing

### ISSUE THREAD

**Issue by jimmyyentran** [fate0/pychrome#6]
I am opening an MongoDB client before importing pychrome.
```python
from pymongo import MongoClient
c = MongoClient("12.12.12.12", 12345)
import pychrome
```
The following error is observed
```
{'_MongoClient__options': <pymongo.client_options.ClientOptions object at 0x1019f51d0>, '_MongoClient__default_database_name': None, '_MongoClient__lock': <unlocked _thread.lock object at 0x101975f08>, '_MongoClient__cursor_manager': None, '_MongoClient__kill_cursors_queue': [], '_event_listeners': <pymongo.monitoring._EventListeners object at 0x1019f5b38>, '_MongoClient__index_cache': {}, '_MongoClient__index_cache_lock': <unlocked _thread.lock object at 0x101975e18>, '_BaseObject__codec_options': CodecOptions(document_class=dict, tz_aware=False, uuid_representation=PYTHON_LEGACY, unicode_decode_error_handler='strict', tzinfo=None), '_BaseObject__read_preference': Primary(), '_BaseObject__write_concern': WriteConcern(), '_BaseObject__read_concern': ReadConcern(), '_MongoClient__all_credentials': {}, '_topology_settings': <pymongo.settings.TopologySettings object at 0x10207ac50>, '_topology': <pymongo.topology.Topology object at 0x102247e80>, '_kill_cursors_executor': <pymongo.periodic_executor.PeriodicExecutor object at 0x10224c978>}
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/jimmytran/.virtualenvs/crypto/lib/python3.6/site-packages/pychrome/browser.py", line 11, in <module>
    from pychrome.tab import Tab
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 154, in __exit__
  File "<frozen importlib._bootstrap>", line 106, in release
RuntimeError: cannot release un-acquired lock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/jimmytran/.virtualenvs/crypto/lib/python3.6/site-packages/pychrome/__init__.py", line 6, in <module>
    from pychrome.browser import Browser
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 154, in __exit__
  File "<frozen importlib._bootstrap>", line 106, in release
RuntimeError: cannot release un-acquired lock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jimmytran/Workspace/crypto/crypto/__main__.py", line 5, in <module>
    import pychrome
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 154, in __exit__
  File "<frozen importlib._bootstrap>", line 106, in release
RuntimeError: cannot release un-acquired lock
```

Removing `#gevent.monkey.patch_thread()` in `tab.py` solves the issue.
```python
import gevent.monkey
gevent.monkey.patch_socket()
# gevent.monkey.patch_thread()
```

**Comment by fate0** [comment]
well. I need to patch_thread, because in `websocket._abnf`:

```
    def recv_frame(self):

        with self.lock:  # threading.Lock
```

I am going to switch back to `threading`

**Comment by jurecuhalev** [comment]
I think I'm seeing similar error in Django:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 131, in finish_response
    self.close()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/simple_server.py", line 36, in close
    SimpleHandler.close(self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 259, in close
    self.result.close()
  File "/Users/gandalf/.virtualenvs/ocwc-members/lib/python2.7/site-packages/django/http/response.py", line 305, in close
    signals.request_finished.send(sender=self._handler_class)
  File "/Users/gandalf/.virtualenvs/ocwc-members/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/gandalf/.virtualenvs/ocwc-members/lib/python2.7/site-packages/django/db/__init__.py", line 94, in close_old_connections
    conn.close_if_unusable_or_obsolete()
  File "/Users/gandalf/.virtualenvs/ocwc-members/lib/python2.7/site-packages/django/db/backends/__init__.py", line 470, in close_if_unusable_or_obsolete
    self.close()
  File "/Users/gandalf/.virtualenvs/ocwc-members/lib/python2.7/site-packages/django/db/backends/__init__.py", line 187, in close
    self.validate_thread_sharing()
  File "/Users/gandalf/.virtualenvs/ocwc-members/lib/python2.7/site-packages/django/db/backends/__init__.py", line 499, in validate_thread_sharing
    % (self.alias, self._thread_ident, thread.get_ident()))
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 123145527988224 and this is thread id 4403486224.
```

Googling turns up: https://code.djangoproject.com/ticket/17998

**Update:** 0.2.1 fixes this for me

**Comment by fate0** [comment]
I switch back to threading, it should fix this issue, try `pip install -U pychrome`
